name = "DiferentialEvolution"
uuid = "181f3fb1-8b97-41c9-a4b8-31033d88b20d"
authors = ["Nicolas Urcelay <nico_mx4@hotmail.com> and contributors"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.6.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
